### ISSUE TITLE
Delete CMApplication

### ISSUE THREAD

**Issue by carlosalbaidiada** [codaamok/PSCMWin10Language#1]
Hi,

I'm, trying to delete a CMApplication package that has been generated and always getting a message that there are depencies of this application, and there is a eternal loop that does not allow you to delete it.

How I should delete it if needed ?

Thanks in advance

**Comment by codaamok** [comment]
Hi, did you try deleting the dependencies for the User deployment type on the System deployment? Open the User's deployment type and go to the Dependencies tab. You'll see what I mean there.

**Comment by carlosalbaidiada** [comment]
Hi, thanks thanks for your quick response.

I've check the deployment type, inside of it, on the Dependencies Tab is in blank, there's no content inside. But I'm still not able to delete the Deployment type or the Application either.

**Comment by codaamok** [comment]
Maybe the System deployment type? I think I got muddled up with wording. Engage thought 😄

**Comment by carlosalbaidiada** [comment]
Hi ¡¡¡

the deployment type for user I was able to delete it, but the deployment type for system is the one that is having problems and I'm not allowed

**Comment by codaamok** [comment]
Did you delete the revisions too?

**Comment by carlosalbaidiada** [comment]
I don't think so,

where could I find it the revisions ?

**Comment by codaamok** [comment]
This should help you https://docs.microsoft.com/en-us/mem/configmgr/apps/deploy-use/revise-and-supersede-applications

**Comment by carlosalbaidiada** [comment]
Yes ¡¡¡

that's it ... the revisions

Thank you so much for your help ¡¡¡¡¡¡¡
