### ISSUE TITLE
Cant remove created applications

### ISSUE THREAD

**Issue by mmtechconsulting** [codaamok/PSCMWin10Language#8]
I have run the powershell script and created the apps without issue. 

I now want to remove them however there is no way possible to delete them because of dependent apps.
![image](https://user-images.githubusercontent.com/95470450/173243199-dfa87a27-39b2-4e5f-ac96-6d5d7049f526.png)

**Comment by codaamok** [comment]
https://github.com/codaamok/PSCMWin10Language/issues/1
